Update packaging/Docker/Dockerfile.dev
Co-authored-by: Leonardo Carreras <88666277+leonardocarreras@users.noreply.github.com>
Signed-off-by: Anas Bahr <91484009+AnasBahr@users.noreply.github.com>

diff --git a/packaging/Docker/Dockerfile.dev b/packaging/Docker/Dockerfile.dev
--- a/packaging/Docker/Dockerfile.dev
+++ b/packaging/Docker/Dockerfile.dev
@@ -83,7 +83,7 @@ RUN set -eux; \
 			exit 1 ;; \
 	esac; \
 	if [ "$(uname -m)" = "x86_64" ]; then \
-		curl -sSL -L --max-time 300 --retry 3 --retry-delay 5 "${libcimpp_url}" -o /tmp/libcimpp.rpm || (echo "Failed to download ${libcimpp_url}" >&2; exit 1); \
+		curl -fsSL --max-time 300 --retry 3 --retry-delay 5 "${libcimpp_url}" -o /tmp/libcimpp.rpm || (echo "Failed to download ${libcimpp_url}" >&2; exit 1); \
 		dnf -y install /tmp/libcimpp.rpm; \
 		rm -f /tmp/libcimpp.rpm; \
 	else \
